/**
 * Trinetra AI Client Service
 * ============================
 * Server-side HTTP client that calls the Trinetra AI analysis endpoints
 * for every outgoing chat message:
 *
 *   text    -> POST /api/analyze-message     (DistilBERT)
 *   url     -> POST /api/analyze-url         (URL / phishing analysis)
 *   image   -> POST /api/analyze-screenshot  (OCR + payment fraud / text scan)
 *   voice   -> POST /api/analyze-voice       (Whisper + DistilBERT)
 *   payment -> POST /api/analyze-upi         (UPI Random Forest)
 *
 * Every function accepts an optional `userId` (the Secure Chat sender's id)
 * which is forwarded to Trinetra for audit/logging purposes.
 *
 * This module is imported ONLY by the message service (server-side).
 * It never runs in the browser and never exposes model internals.
 *
 * Failure modes are handled gracefully: if Trinetra AI is unreachable,
 * times out, or returns an error, the message is still delivered
 * (without analysis) rather than being blocked.
 */

import { promises as fs } from "fs"
import path from "path"
import type { TrinetraAnalysisResult } from "@/types"

// ─── Configuration ──────────────────────────────────────────────────────────

/** Base URL of the Trinetra AI Flask backend (no trailing slash). */
const TRINETRA_BASE_URL =
  process.env.TRINETRA_API_URL ?? "http://localhost:5000"

/** Maximum time to wait for text/image/UPI/URL analysis. */
const TRINETRA_TIMEOUT_MS = Number(
  process.env.TRINETRA_TIMEOUT_MS ?? 15_000,
)

/** Voice transcription (Whisper) can take much longer on CPU. */
const TRINETRA_VOICE_TIMEOUT_MS = Number(
  process.env.TRINETRA_VOICE_TIMEOUT_MS ?? 60_000,
)

/** Local uploads directory managed by /api/upload. */
const UPLOADS_DIR = path.join(process.cwd(), "uploads")

/**
 * Filenames are generated by /api/upload as <32 hex chars>.<ext>.
 * Validating against this pattern blocks path traversal when reading
 * the file back for analysis.
 */
const MEDIA_FILENAME_RE = /^[a-f0-9]{32}\.(png|jpe?g|webp|gif|webm|ogg|mp3|wav|m4a|mp4)$/i

// ─── Response shape from Trinetra AI ────────────────────────────────────────

interface TrinetraApiResponse {
  success: boolean
  verdict?: string
  prediction?: string
  confidence?: number
  safe_probability?: number | null
  scam_probability?: number | null
  transcription?: string
  reasons?: string[]
  reason?: string
  red_flags?: string[]
  indicators?: string[]
  signals?: string[]
  explanation?: string
  ocr_text?: string
  extracted_text?: string
  text?: string
  detected_urls?: string[]
  urls?: string[]
  qr_content?: string | null
  qr_data?: string | null
  content?: string | null
  decoded_content?: string | null
  language?: string | null
  speech_text?: string | null
  speechText?: string | null
  language_code?: string | null
  error?: string
}

// ─── Internal helpers ────────────────────────────────────────────────────────

function collectSignalTexts(value: unknown): string[] {
  if (!value) return []
  if (typeof value === "string") return value.trim() ? [value.trim()] : []
  if (!Array.isArray(value)) return []
  const texts: string[] = []
  for (const item of value) {
    if (typeof item === "string" && item.trim()) {
      texts.push(item.trim())
      continue
    }
    if (item && typeof item === "object") {
      const record = item as Record<string, unknown>
      const text = record.description ?? record.reason ?? record.label ?? record.message
      if (typeof text === "string" && text.trim()) texts.push(text.trim())
    }
  }
  return texts
}

function collectReasons(data: TrinetraApiResponse): string[] {
  return [
    ...new Set([
      ...collectSignalTexts(data.reasons),
      ...collectSignalTexts(data.reason),
      ...collectSignalTexts(data.red_flags),
      ...collectSignalTexts(data.indicators),
      ...collectSignalTexts(data.signals),
      ...collectSignalTexts(data.explanation),
    ]),
  ]
}

function normalizeLanguage(value: string | null | undefined): string | null {
  const language = value?.trim().toLowerCase().split(/[-_]/)[0]
  return language || null
}

function toResult(data: TrinetraApiResponse): TrinetraAnalysisResult | null {
  if (!data.success || (!data.verdict && !data.prediction)) return null
  const prediction = (data.verdict ?? data.prediction ?? "").trim().toUpperCase()
  const normalizedPrediction =
    prediction === "FAKE" || prediction === "FRAUD" || prediction === "UNSAFE"
      ? "SCAM"
      : prediction
  if (
    normalizedPrediction !== "SAFE" &&
    normalizedPrediction !== "SCAM" &&
    normalizedPrediction !== "SUSPICIOUS"
  ) {
    return null
  }
  return {
    prediction: normalizedPrediction,
    confidence: data.confidence ?? 0,
    safeProbability: data.safe_probability ?? null,
    scamProbability: data.scam_probability ?? null,
    ocrText: data.ocr_text ?? data.extracted_text ?? data.text ?? null,
    detectedUrls: data.detected_urls ?? data.urls ?? [],
    qrContent:
      data.qr_content ??
      data.qr_data ??
      data.decoded_content ??
      data.content ??
      null,
    reasons: collectReasons(data),
    language: normalizeLanguage(data.language ?? data.language_code),
    speechText: data.speech_text ?? data.speechText ?? null,
  }
}

/** POST to Trinetra with timeout; returns parsed JSON or null on failure. */
async function postToTrinetra(
  url: string,
  init: RequestInit,
  timeoutMs: number,
): Promise<TrinetraApiResponse | null> {
  if (!TRINETRA_BASE_URL) {
    console.log("[trinetra] Analysis disabled (no TRINETRA_API_URL)")
    return null
  }

  try {
    const controller = new AbortController()
    const timeoutId = setTimeout(() => controller.abort(), timeoutMs)

    const response = await fetch(url, { ...init, signal: controller.signal })
    clearTimeout(timeoutId)

    if (!response.ok) {
      const body = (await response.json().catch(() => ({}))) as TrinetraApiResponse
      console.warn(
        `[trinetra] HTTP ${response.status}: ${body.error ?? "unknown error"}`,
      )
      return null
    }

    return (await response.json()) as TrinetraApiResponse
  } catch (err) {
    if (err instanceof DOMException && err.name === "AbortError") {
      console.warn(`[trinetra] Timeout after ${timeoutMs}ms`)
    } else {
      console.warn("[trinetra] Analysis request failed:", (err as Error).message)
    }
    return null
  }
}

/** Read a media file from the uploads dir after validating its URL. */
async function readMediaFile(
  mediaUrl: string,
): Promise<{ buffer: Buffer; filename: string } | null> {
  const match = /^\/api\/files\/(.+)$/.exec(mediaUrl ?? "")
  const filename = match?.[1]
  if (!filename || !MEDIA_FILENAME_RE.test(filename)) {
    console.warn("[trinetra] Rejected media URL (invalid filename pattern)")
    return null
  }
  try {
    const buffer = await fs.readFile(path.join(UPLOADS_DIR, filename))
    return { buffer, filename }
  } catch {
    console.warn(`[trinetra] Media file not found: ${filename}`)
    return null
  }
}

// ─── 1. Text analysis (DistilBERT) ──────────────────────────────────────────

export async function analyzeMessage(
  content: string,
  userId?: string,
  language?: string,
): Promise<TrinetraAnalysisResult | null> {
  const data = await postToTrinetra(
    `${TRINETRA_BASE_URL}/api/analyze-message`,
    {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        message: content,
        ...(userId ? { user_id: userId } : {}),
        ...(language ? { language } : {}),
      }),
    },
    TRINETRA_TIMEOUT_MS,
  )
  return data ? toResult(data) : null
}

// ─── 2. URL analysis (phishing / malicious-link detection) ──────────────────

export async function analyzeUrl(
  url: string,
  userId?: string,
  language?: string,
): Promise<TrinetraAnalysisResult | null> {
  const data = await postToTrinetra(
    `${TRINETRA_BASE_URL}/api/analyze-url`,
    {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        url,
        ...(userId ? { user_id: userId } : {}),
        ...(language ? { language } : {}),
      }),
    },
    TRINETRA_TIMEOUT_MS,
  )
  return data ? toResult(data) : null
}

// ─── 3. Image analysis (OCR + payment fraud / text scan) ────────────────────

export async function analyzeImage(
  mediaUrl: string,
  userId?: string,
  language?: string,
): Promise<TrinetraAnalysisResult | null> {
  const media = await readMediaFile(mediaUrl)
  if (!media) return null

  const form = new FormData()
  form.append("image", new Blob([new Uint8Array(media.buffer)]), media.filename)
  if (userId) form.append("user_id", userId)
  if (language) form.append("language", language)

  const data = await postToTrinetra(
    `${TRINETRA_BASE_URL}/api/analyze-screenshot`,
    { method: "POST", body: form },
    TRINETRA_TIMEOUT_MS,
  )
  if (!data) return null

  const screenshotResult = toResult(data)
  const extractedText = data.ocr_text ?? data.extracted_text ?? data.text

  // OCR text must use the same text model and preprocessing as normal chat text.
  // The screenshot endpoint remains responsible for QR/URL metadata only.
  if (!extractedText?.trim()) return screenshotResult

  const textResult = await analyzeMessage(extractedText, userId, language)
  if (!textResult) return null

  return {
    ...textResult,
    ocrText: extractedText,
    detectedUrls: screenshotResult?.detectedUrls ?? [],
    qrContent: screenshotResult?.qrContent ?? null,
    reasons: textResult.reasons,
  }
}

// ─── 4. Voice analysis (Whisper + DistilBERT) ───────────────────────────────

export async function analyzeVoice(
  mediaUrl: string,
  userId?: string,
  language?: string,
): Promise<{ result: TrinetraAnalysisResult | null; transcription: string | null }> {
  const media = await readMediaFile(mediaUrl)
  if (!media) return { result: null, transcription: null }

  const form = new FormData()
  form.append("audio", new Blob([new Uint8Array(media.buffer)]), media.filename)
  if (userId) form.append("user_id", userId)
  if (language) form.append("language", language)

  const data = await postToTrinetra(
    `${TRINETRA_BASE_URL}/api/analyze-voice`,
    { method: "POST", body: form },
    TRINETRA_VOICE_TIMEOUT_MS,
  )
  if (!data) return { result: null, transcription: null }
  return {
    result: toResult(data),
    transcription: data.transcription ?? null,
  }
}

// ─── 5. Payment request analysis (UPI Random Forest) ────────────────────────

export async function analyzeUpi(
  upiId: string,
  amount: number,
  note: string,
  userId?: string,
  language?: string,
): Promise<TrinetraAnalysisResult | null> {
  const data = await postToTrinetra(
    `${TRINETRA_BASE_URL}/api/analyze-upi`,
    {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        upi_id: upiId,
        amount,
        note,
        ...(userId ? { user_id: userId } : {}),
        ...(language ? { language } : {}),
      }),
    },
    TRINETRA_TIMEOUT_MS,
  )
  return data ? toResult(data) : null
}
