import { NextRequest, NextResponse } from "next/server"
import { createReadStream } from "fs"
import { stat } from "fs/promises"
import path from "path"
import { Readable } from "stream"
import { getUserId } from "@/lib/auth-utils"

/**
 * GET /api/files/[filename]
 * Serve an uploaded chat attachment (image or voice note) to authenticated users.
 *
 * Supports HTTP Range requests so the browser audio player can seek
 * within voice messages.
 */

const UPLOADS_DIR = path.join(process.cwd(), "uploads")

// Only files generated by /api/upload — blocks path traversal and probing
const SAFE_FILENAME = /^[a-f0-9]{32}\.(png|jpe?g|webp|gif|webm|ogg|mp3|wav|m4a|mp4)$/i

const MIME_BY_EXT: Record<string, string> = {
  png: "image/png",
  jpg: "image/jpeg",
  jpeg: "image/jpeg",
  webp: "image/webp",
  gif: "image/gif",
  webm: "audio/webm",
  ogg: "audio/ogg",
  mp3: "audio/mpeg",
  wav: "audio/wav",
  m4a: "audio/mp4",
  mp4: "audio/mp4",
}

export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ filename: string }> },
) {
  try {
    await getUserId()
  } catch (err) {
    if (err instanceof Error && err.message === "Unauthorized") {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 })
    }
    console.error("[GET /api/files]", err)
    return NextResponse.json({ error: "Internal server error" }, { status: 500 })
  }

  const { filename } = await params

  if (!SAFE_FILENAME.test(filename)) {
    return NextResponse.json({ error: "Invalid filename" }, { status: 400 })
  }

  const filePath = path.join(UPLOADS_DIR, filename)

  let fileStat
  try {
    fileStat = await stat(filePath)
  } catch {
    return NextResponse.json({ error: "File not found" }, { status: 404 })
  }

  const ext = (filename.split(".").pop() ?? "").toLowerCase()
  const contentType = MIME_BY_EXT[ext] ?? "application/octet-stream"
  const total = fileStat.size

  // ── Range request (partial content, used by <audio> for seeking) ─────────
  const rangeHeader = request.headers.get("range")
  if (rangeHeader) {
    const match = /bytes=(\d*)-(\d*)/.exec(rangeHeader)
    if (match) {
      let start = match[1] ? parseInt(match[1], 10) : 0
      let end = match[2] ? parseInt(match[2], 10) : total - 1
      start = Math.max(0, Math.min(start, total - 1))
      end = Math.max(start, Math.min(end, total - 1))

      const stream = createReadStream(filePath, { start, end })
      return new NextResponse(Readable.toWeb(stream) as ReadableStream, {
        status: 206,
        headers: {
          "Content-Type": contentType,
          "Content-Length": String(end - start + 1),
          "Content-Range": `bytes ${start}-${end}/${total}`,
          "Accept-Ranges": "bytes",
          "Cache-Control": "private, max-age=86400",
        },
      })
    }
  }

  // ── Full file ──────────────────────────────────────────────────────────────
  const stream = createReadStream(filePath)
  return new NextResponse(Readable.toWeb(stream) as ReadableStream, {
    status: 200,
    headers: {
      "Content-Type": contentType,
      "Content-Length": String(total),
      "Accept-Ranges": "bytes",
      "Cache-Control": "private, max-age=86400",
    },
  })
}
