import { NextRequest, NextResponse } from "next/server"
import { get } from "@vercel/blob"
import { getUserId } from "@/lib/auth-utils"

/**
 * GET /api/files/[filename]
 * Serve an uploaded chat attachment (image or voice note) to authenticated users.
 *
 * Supports HTTP Range requests so the browser audio player can seek
 * within voice messages.
 */

// Only files generated by /api/upload — blocks path traversal and probing
const SAFE_FILENAME = /^[a-f0-9]{32}\.(png|jpe?g|webp|gif|webm|ogg|mp3|wav|m4a|mp4)$/i

const MIME_BY_EXT: Record<string, string> = {
  png: "image/png",
  jpg: "image/jpeg",
  jpeg: "image/jpeg",
  webp: "image/webp",
  gif: "image/gif",
  webm: "audio/webm",
  ogg: "audio/ogg",
  mp3: "audio/mpeg",
  wav: "audio/wav",
  m4a: "audio/mp4",
  mp4: "audio/mp4",
}

export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ filename: string }> },
) {
  try {
    await getUserId()
  } catch (err) {
    if (err instanceof Error && err.message === "Unauthorized") {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 })
    }
    console.error("[GET /api/files]", err)
    return NextResponse.json({ error: "Internal server error" }, { status: 500 })
  }

  const { filename } = await params

  if (!SAFE_FILENAME.test(filename)) {
    return NextResponse.json({ error: "Invalid filename" }, { status: 400 })
  }

  const range = request.headers.get("range")
  let blob
  try {
    blob = await get(filename, {
      access: "private",
      headers: range ? { range } : undefined,
    })
  } catch {
    return NextResponse.json({ error: "Unable to retrieve file" }, { status: 502 })
  }
  if (!blob) return NextResponse.json({ error: "File not found" }, { status: 404 })

  const contentType = blob.blob.contentType || MIME_BY_EXT[(filename.split(".").pop() ?? "").toLowerCase()]
  const headers = new Headers({
    "Content-Type": contentType || "application/octet-stream",
    "Accept-Ranges": "bytes",
    "Cache-Control": "private, max-age=86400",
  })
  const contentLength = blob.headers.get("content-length")
  const contentRange = blob.headers.get("content-range")
  if (contentLength) headers.set("Content-Length", contentLength)
  if (contentRange) headers.set("Content-Range", contentRange)

  return new NextResponse(blob.stream, {
    status: contentRange ? 206 : 200,
    headers,
  })
}
